### ISSUE TITLE
Jobs with disk reservation

### ISSUE THREAD

**Issue by ghost** [grid5000/g5k-api#35]
I added a job with disk reservation in branch bug8029_add_disk_resources (from branch jessie) and changed some tests so that they pass.
Two tests still fail, for which I don't know what is the expected behavior.

**Comment by dmargery** [comment]
Could you rebase your work on branch rebased-jessie-devel so I can meaningfully compare the two branches ?

**Comment by f-didier** [comment]
I've done it in branch bug8029_rebased_add_disk_resources.

**Comment by dmargery** [comment]
Hello,

thank you, the diff is much easier to understand. 

I have reproduced the 2 failing tests. 

Bug with 'OAR::Resource should return the status of all the resources' is linked to the fact that the fixture expects that the job you introduced (#379625) is supposed to be running, but parasilo-1 (the node with disks you added) is free. I could not get from reading the diff whether job #379625 is supposed to be a job with cpu resources, or a disk only job. From the changes to assigned_resources, it seems cores are included in the job. Therefore, the test failure is an indication of a bug in the implementation (the node should not seem free) rather than a problem with test data.

Bug with  'OAR::Resource should return all nodes with status free' has the same issue (parasilo-1.rennes.grid5000.fr) should not be in the list of free nodes

David

**Comment by f-didier** [comment]
Hello,

I corrected some mistakes I made in the test database for disk
resources.  Indeed, the network address field of disk resources must be
set to "" (blank). As you guessed, job #379625 is a job with cpu
resources. The same two tests still fail with the introduction of the
blank value.

**Comment by dmargery** [comment]
To keep a trace of our XMPP exchanges : with the changes, the tests correctly catch implementation issues : the API is not able to represent the status of a resource of an other type than nodes, but the implementation understands disks as being nodes with an empty name.

2 ways forward:

1. change implementation so that the API does not see disks as a node resource
1. augment the json output to include a "disks" entry at the level of "nodes", with the status of disks.

If the second option is chosen, "vlans" and "subnets" entries should be considered as a useful addition to the API, as in

```json
{
   "links" : [
      {
         "type" : "application/vnd.grid5000.item+json",
         "href" : "/3.0/sites/nantes/status",
         "rel" : "self"
      },
      {
         "rel" : "parent",
         "href" : "/3.0/sites/nantes",
         "type" : "application/vnd.grid5000.item+json"
      }
   ],
   "uid" : 1498051233,
   "nodes": {
....},
   "disks": {
...},
    "vlans": {
...},
   "subnets": {
...}
}
```

**Comment by snoir** [comment]
This has been added in g5k-api at some time, by putting into JSON `disks`, `vlans` and `subnets`.
